### ISSUE TITLE
OmegaTrajectorySegmentation segments labels are incorrect

### ISSUE THREAD

**Issue by strambc** [OmegaProject/Omega#163]
![omega_artiftraj_mixed_2_segmentation labels](https://cloud.githubusercontent.com/assets/4050585/23385682/82832232-fd1f-11e6-8f9f-4451063e453e.PNG)
Labels for segments do not make sense

**Comment by Akramhar** [comment]
Should be solved in release 0.22

**Comment by strambc** [comment]
Labels are now correct but still not visible because of too little space.
