### ISSUE TITLE
OmegaTrajectoryMeasures_Diffusivity window resizing and refreshing issues

### ISSUE THREAD

**Issue by strambc** [OmegaProject/Omega#173]
- In both Motion Type and Diffusivity the legend windows are dominant over the graph windows causing squeezing and distortions (see attached screen shot).
- In Motion Type resizing when changing size of window is not automatic but requires clicking anywhere on the screen.
- In Diffusivity resizing is fine and automatic.
- In both Diffusivity and in Motion Type in order to re-draw a graph after switching between Segmentation runs one has to change graph type and requires multiple clicks.
-Re drwaing graphs is sloppy in most cases
-When a segmentation run does not have a Tracking Measure run the graph should be blank, instead it retains last selection

**Comment by strambc** [comment]
![window resizing_screen shot 1](https://cloud.githubusercontent.com/assets/4050585/23679162/0294add4-0355-11e7-8189-84b73ab6aca4.png)
![window resizing_screen shot 2](https://cloud.githubusercontent.com/assets/4050585/23679164/0295c17e-0355-11e7-908b-214168c0b657.png)
![window resizing_screen shot 3](https://cloud.githubusercontent.com/assets/4050585/23679163/02951788-0355-11e7-8ebf-cbf23d2f807b.png)

**Comment by Akramhar** [comment]
should be fixed in the omega-0.27

**Comment by strambc** [comment]
Problems still present:

- In both Motion Type and Diffusivity the legend windows are dominant over the graph windows causing squeezing and distortions (see attached screen shot).

**Comment by strambc** [comment]
Point 1 is still present.
Issue closed but point 1 was moved to a new issue --> #247
