### ISSUE TITLE
OmegaTrajectorySegmenation motion type selection is remembered even in Spot mode

### ISSUE THREAD

**Issue by strambc** [OmegaProject/Omega#174]
1. --When in Spot selection mode the motion type of previous selection is remembered and applied to next selection. This is annoying because in Spot mode the motion type should be selected after the selection of the segment.
3. --When then one tries to select a different motion type the view shifts to the side.
4. --Apparently remembers the selection even across different segmentation runs (last motion type selected by the tool in general)
5. --Would be great to be able to add a "Select Last" button on top to aide segmentaion

**Comment by Akramhar** [comment]
Point 1, 3 and 4 seems to be fixed in omega-0.25

**Comment by Akramhar** [comment]
point 2 should be fixed in omega-0.26

**Comment by strambc** [comment]
VERSION 025
Point 4: DONE
Point 3: still a problem
Point 1: much better but there is still a glitch. Sometimes it get stuck again. Trying to understand how to reproduce

**Comment by Akramhar** [comment]
Im confused here.
Point 3) Yes the selection remain but it doesn't behave in weird way like before and the selected motion type should always be displayed at the bottom.

Point 1) I don't understand if its ok ("--> OK") or if there is a glitch.

**Comment by strambc** [comment]
Again:
point 2 and 4 are solved.

Points 1 and 3 are still a problem
