### ISSUE TITLE
TMeas Diffusivity: faulty selection on TB 

### ISSUE THREAD

**Issue by strambc** [OmegaProject/Omega#242]
Same case as  #240

When trajectories are selected on the Tracking Measures Diffusivity TB the selection persists on the image on the Side Bar even when the selection is altered in the TB in a different plugin.
For example behavior appeared when the TS plugin was opened and attempt was made to select a different trajectory from a different PL run
![screen shot 2017-04-25 at 17 45 00](https://cloud.githubusercontent.com/assets/4050585/25409176/efc7fdae-29de-11e7-8cee-e39f4eb59249.png)

**Comment by strambc** [comment]
OBSERVATION:
when trajectories on TM Diffusivity TB were deselected at least one always remained selected and selection on the TS TB was not taken into account.

![screen shot 2017-04-25 at 17 46 26](https://cloud.githubusercontent.com/assets/4050585/25409265/405b75e8-29df-11e7-8680-65975e1679b6.png)

**Comment by Akramhar** [comment]
should be solved in omega-0.34

**Comment by strambc** [comment]
Not solved. Behavior very similar to #258.
Might be connected.
Will close this and merge remaining issues here with that issue.
