### ISSUE TITLE
OmegaTrackingMeasures: issues remaining on graphs selector combo-boxes

### ISSUE THREAD

**Issue by strambc** [OmegaProject/Omega#303]
Inherits from #262 

1 minor issue remaining with combo box for Diffusivity

ORDER of 
"Uncertainty   of OCD2 estimation" and 
"Uncertainty of Slope MSS estimation" is currently inverted.

Refer to attached spreadsheet for issues remaining: look at ORANGE TAB

[2017-10-16_Tracking_Measures_menu_lables_verification_v08_tested.xlsx](https://github.com/OmegaProject/Omega/files/1389162/2017-10-16_Tracking_Measures_menu_lables_verification_v08_tested.xlsx)

**Comment by Akramhar** [comment]
should be fixed in omega-0.37

**Comment by strambc** [comment]
Order is still wrong:
Wrong order
1. Slope of log-log MSD vs. ∂t Plot
2. Observed Diffusion Constant of  Order 2 (Logaritmic Intercept)
3. Slope of the Moment Scaling Spectrum
4. Uncertainty of Slope MSS estimation
5. Uncertainty of OCD2 estimation
|
\/
Right order
1. Slope of log-log MSD vs. ∂t Plot
2. Observed Diffusion Constant of  Order 2 (Logaritmic Intercept)
3. Slope of the Moment Scaling Spectrum
4. Uncertainty of OCD2 estimation
5. Uncertainty of Slope MSS estimation

**Comment by Akramhar** [comment]
should be fixed in omega-0.38
